R01/d42/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("intranet.urls")),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

R01/intranet/urls.py
from django.urls import path
from . import views

from intranet import views

app_name = "intranet"

urlpatterns = [
    path('', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('register/', views.Register.as_view(), name="register"),
    path('home/', views.Home.as_view(), name="home"),
    path('home/new/',views.New_topic.as_view(),name='new_topic'),
    path('home/<int:forum_id>/',views.forum_Detail.as_view(),name='forum_detail'),
    path('home/delete_forum/<int:forum_id>/', views.Delete_forum.as_view(),name='delete_forum'),
    path('create_comment/<int:current_id>/',views.Create_comment.as_view(),name='create_comment'),
    path('delete_comment/<int:com_id>/<int:current_id>', views.Delete_comment.as_view() , name="delete_comment"),
    path('create_recomment/<int:current_id>', views.Create_recomment.as_view() , name="create_recomment"),
    path('delete_recomment/<int:recom_id>/<int:current_id>', views.Delete_recomment.as_view() , name="delete_recomment"),
    path('profile/<int:forum_id>',views.ProfileView.as_view(),name='profile'),
]

R01/intranet/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile_user',on_delete=models.CASCADE, null=False, primary_key=True, unique=True)
    image = models.ImageField(null=True, blank=True)
    description = models.TextField(default='',null=True, blank=True)

# 게시판 화면.
class Topic(models.Model):
    objects = models.Manager()
    message = models.TextField(max_length=5000,null=True)
    subject = models.CharField(max_length=255)
    last_updated =  models.DateTimeField(auto_now_add=True, null=True)
    writter = models.ForeignKey(User, related_name='topics',on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ["-last_updated"]

    def __str__(self):
        return self.subject


# ForeignKey : 외래키.
# auto_now_add : 시간 기록.

# 댓글.
class Comment(models.Model):
    objects = models.Manager()
    post = models.ForeignKey(Topic, on_delete=models.CASCADE)
    body = models.CharField('댓글',max_length=150)
    created_at = models.DateTimeField(auto_now=True)
    writter = models.ForeignKey(User, related_name='Comment',on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.body


class ReComment(models.Model):
    objects = models.Manager()
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    body = models.CharField('대댓글',max_length=150)
    created_at = models.DateTimeField(auto_now=True)
    writter = models.ForeignKey(User, related_name='ReComment',on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.body

R01/intranet/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from intranet.models import Comment, ReComment, Profile

class ProfileForm(forms.ModelForm):
    surname=forms.CharField(required=False,max_length=50)
    name=forms.CharField(required=False,max_length=50)
    email=forms.EmailField(required=False,max_length=50)
    class Meta:
        model = Profile
        fields = ('surname','name','email','image','description')

class NewUserForm(UserCreationForm):

	class Meta:
		model = User
		fields = ("username", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		if commit:
			user.save()
		return user


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('body',)


class ReCommentForm(forms.ModelForm):

    class Meta:
        model = ReComment
        fields = ('body','comment')

R01/intranet/views/create_comment.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate
from ..models import Topic, Comment
from ..forms import CommentForm


class Create_comment(View):

    def get(self, request, current_id):
        return redirect('intranet:forum_detail', current_id)

    def post(self, request, current_id):
        filled_form = CommentForm(request.POST)
        if filled_form.is_valid():
            temp_form = filled_form.save(commit=False)
            temp_form.post = Topic.objects.get(id = current_id)
            temp_form.writter = self.request.user
            temp_form.save()
        return redirect('intranet:forum_detail', current_id)

R01/intranet/views/create_recomment.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate
from ..models import Topic, Comment
from ..forms import CommentForm, ReCommentForm


class Create_recomment(View):

    def get(self, request, current_id):
        return redirect('intranet:forum_detail', current_id)

    def post(self, request, current_id):
        filled_form = ReCommentForm(request.POST)
        if filled_form.is_valid():
            temp_form = filled_form.save(commit=False)
            temp_form.writter = self.request.user
            temp_form.save()
        return redirect('intranet:forum_detail', current_id)

R01/intranet/views/delete_comment.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate
from ..models import Topic, Comment
from ..forms import CommentForm

class Delete_comment(View):

    def get(self, request, com_id, current_id):
        mycom = Comment.objects.get(id = com_id)
        mycom.delete()
        return redirect('intranet:forum_detail', current_id)

R01/intranet/views/delete_forum.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from ..models import Topic


class Delete_forum(View):

    def get(self, redirect, forum_id):
        mycom = Topic.objects.get(id = forum_id)
        mycom.delete()
        return HttpResponseRedirect('/home/')

R01/intranet/views/delete_recomment.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate
from ..models import Topic, Comment, ReComment
from ..forms import CommentForm, ReCommentForm

class Delete_recomment(View):

    def get(self, request, recom_id, current_id):
        mycom = ReComment.objects.get(id = recom_id)
        mycom.delete()
        return redirect('intranet:forum_detail', current_id)

R01/intranet/views/forum_detail.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate
from ..models import Topic, Comment
from ..forms import CommentForm, ReCommentForm


class forum_Detail(View):
    """
    게시글 세부내용 출력
    """
    template_name = 'intra/forum_Detail.html'

    def get(self, request, forum_id):
        forum = get_object_or_404(Topic, pk=forum_id)
        mycom_form = CommentForm()
        myrecom_form = ReCommentForm()
        current = Topic.objects.get(id = forum_id)
        context = {
            'forum' : forum,
            'comment_form':mycom_form,
            'current':current,
            'recomment_form': myrecom_form,
            }
        return render(request, self.template_name, context)

R01/intranet/views/home.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib.auth import login, logout, authenticate
from  ..models import Topic
from django.core.paginator import Paginator

class Home(View):
    """
    게시글 목록출력
    """
    template_name = 'intra/home.html'

    def get(self, request):
        page = request.GET.get('page', '1')
        topics = Topic.objects.all()
        paginator = Paginator(topics, 10)
        page_obj = paginator.get_page(page)
        context = {'topics': page_obj}
        return render(request, self.template_name, context)

R01/intranet/views/index.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View

#['get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace']

class Index(View):

    template_name = 'index.html'

    def get(self, request):
        return render(request, self.template_name)

R01/intranet/views/login.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib import messages #import messages
from django.contrib.auth import login, logout, authenticate


class Login(View):

    template_name = 'login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('intranet:home')
        form = AuthenticationForm()
        return render(request, self.template_name, context={"login_form":form})


    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("intranet:home")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
        return redirect("intranet:login")

R01/intranet/views/logout.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.forms import AuthenticationForm #add this
from django.contrib import messages #import messages
from django.contrib.auth import login, logout, authenticate


class Logout(View):

    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("intranet:login")

R01/intranet/views/new_topic.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from  ..models import Topic
from django.views.generic import ListView

class New_topic(ListView):
    """
    게시글 작성.
    """
    template_name = 'intra/new_topic.html'

    def get(self, request):
        topics = Topic.objects.all()
        context = {'topics': topics}
        return render(request, self.template_name, {'topics':topics})

    def post(self, request):
        topics = Topic.objects.all()
        if request.method =='POST':
            subject = request.POST['subject']
            message = request.POST['message']

            user = self.request.user
            print("=====================================")
            print("message = ", message)
            print("=====================================")
            topic = Topic.objects.create(
                subject=subject,
                message=message,
                writter=user
            )

            return redirect('intranet:home')

R01/intranet/views/profile.py
from  ..models import Topic, Profile
from ..forms import ProfileForm
from django.shortcuts import render
from django.shortcuts import render
from django.views.generic import ListView

class ProfileView(ListView):
    template_name = 'intra/profile.html'
    form_class=ProfileForm
    context_object_name='object_list'
    queryset = Profile.objects.all()

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        return context


    def post(self, request, forum_id):

        self.object_list = self.get_queryset()
        context = self.get_context_data()


        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                f = form.save(commit=False)
                f.user = request.user
                f.save()
                u = request.user
                u.email = form.cleaned_data['email']
                u.first_name = form.cleaned_data['surname']
                u.last_name = form.cleaned_data['name']
                u.save()

            except Exception as e:
                print("e",e)

        
        forums = Topic.objects.filter(id=forum_id)
        profile = Profile.objects.filter(user=forums[0].writter)
        profile = profile[0]
        context['user_profile'] = profile

        context['form'] = ProfileForm()
        return self.render_to_response(context)

    def get(self, request, forum_id):
        self.object_list = self.get_queryset()
        try:
            forums = Topic.objects.filter(id=forum_id)
            context = {}
            try:
                profile = Profile.objects.filter(user=forums[0].writter)
                profile = profile[0]
            except Exception as e:
                profile = Profile(user=forums[0].writter)
            if not profile:
                profile = Profile(user=forums[0].writter)
            context['user_profile'] = profile

            if profile.user == request.user:
                context['form'] = ProfileForm()
        except Exception as e:
            print(e)
        
        return render(request, self.template_name, context)

R01/intranet/views/register.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from ..forms import NewUserForm
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages #import messages


class Register(View):

    template_name = 'register.html'

    def get(self, request):
        form = NewUserForm
        return render (request, self.template_name, context={"register_form":form})

    def post(self, request):
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect("intranet:home")
        messages.error(request, "Unsuccessful registration. Invalid information.")
        return render (request, self.template_name, context={"register_form":form})

R01/intranet/templates/intra/base.html
{% load static %} {% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    {% endblock %}
    <meta charset="UTF-8">
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"></script>
    {% bootstrap_css %} {% bootstrap_javascript %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class ="navbar-brand" href="\">장고 게시판</a>
        {% if user.is_staff %}
        <a class ="navbar-brand" href="/admin">관리자설정</a>
        {% endif %}
        <a class ="navbar-brand" href="/logout"> LOGOUT </a>
    </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
 </body>
</html>

R01/intranet/templates/intra/forum_Detail.html
{% extends  'intra/base.html' %}
{% if data %}
{% block content %}

<article>
    <div class="container" role="main">
        <h2>{{forum.subject}}</h2>
        <h5><a href="{% url 'intranet:profile' forum.id %}">{{forum.writter.username}}</a></h5>
        <div class="bg-white rounded shadow-sm">
            <div class="board_title"><c:out value="${boardContent.title}"/></div>
            <div class="board_info_box">
                <span class="board_author"><c:out value="${boardContent.reg_id}"/>{{forum.last_updated}}</span><span class="board_date"><c:out value="${boardContent.reg_dt}"/></span>
            </div>
            <br>
            </br>
            <div class="board_content">{{forum.message}}</div>
            <br>
            </br>
        </div>
        <div style="margin-top : 20px">
            <a class="btn btn-sm btn-primary" href="{% url 'intranet:delete_forum' forum.id %}">
                삭제
            </a>
        </div>
    </div>
</article>
<br>
</br>
<form method="post" action="{% url 'intranet:create_comment' forum.id %}">
    {%csrf_token%}
    {{comment_form}}
    <input class="btn btn-sm btn-primary" type="submit">
</form>
<br>
</br>
{% for i in forum.comment_set.all %}

<p><a href="#">ID : {{ i.writter.username }}</a></p>
<p>-> {{i}} </p>
<p> {{ i.created_at }} <a href="{% url 'intranet:delete_comment' i.id forum.id %}"> 삭제 </a> </p>

    <form method="post" action="{% url 'intranet:create_recomment' forum.id %}">
        {%csrf_token%}
        {% for recom_form in recomment_form %}
            {%if recom_form.label != 'Comment' %}
            {{recom_form.label}} : {{recom_form}}
            {%endif%}
        {%endfor%}
        <input type="hidden" name="comment" value={{i.id}}>
        <input class="btn btn-sm btn-primary" type="submit">
    </form>
    {%for recom in i.recomment_set.all %}
        <br><a href="#"> ID : {{ recom.writter.username }}</a></br>
        <br>↪{{recom}}</br>
        <p> {{ recom.created_at }} <a href="{% url 'intranet:delete_recomment' recom.id forum.id %}"> 삭제 </a> </p>
    {%endfor%}
<hr>
{%endfor%}

{% endblock %}
{% endif %}

R01/intranet/templates/intra/home.html
{% extends  'intra/base.html' %}
{% if topics %}


{% block content %}
<table class="table">
    <thead class="bg-info">
        <tr>
            <th>제목</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th>작성자</th>
            <th>작성일자</th>
        </tr>
    </thead>
    <tbody>
        {% for topic in topics %}
        <tr>
            <td>
                <a href="{% url 'intranet:forum_detail' topic.id %}">{{topic.subject }}</a>
            </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a href="{% url 'intranet:profile' topic.id %}">{{topic.writter.username }}</a>
            </td>
            <td>{{topic.last_updated}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<nav>

<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if topics.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ topics.previous_page_number }}">이전</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in topics.paginator.page_range %}
        {% if page_number == topics.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
        {% endif %}
    {% endfor %}
        <!-- 다음페이지 -->
    {% if topics.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ topics.next_page_number }}">다음</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
    {% endif %}
</ul>

<!-- add creating posting button  게시글 버튼-->
<div class="mb-4">
    <a href="new" class="btn btn-info"><b>글 작성</b></a>
</div>

{% endblock %}
{% endif %}

R01/intranet/templates/intra/new_topic.html
{% extends  'intra/base.html' %}



{% block content %}
<form method ="post">
        {% csrf_token %}
        <!-- writting title -->
        <div class="form-group">
            <label for="id_subject"> 제목 </label>
            <input type="text" class="form-control" id="id_subject" name="subject">
        </div>

        <div class="form-group">
            <lable for="id_message">내용</lable>
            <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-success">게시</button>
</form>
{% endblock %}

R01/intranet/templates/intra/profile.html
{% extends  'intra/base.html' %}


{% block content %}
<h2>내 정보</h2>
<ul>
    <li>username : {{ user_profile.user }}  </li>
    <li>surname : {{ user_profile.user.first_name }}  </li>
    <li>name : {{ user_profile.user.last_name }}  </li>
    <li>email : {{ user_profile.user.email }}  </li>
    <li>description : {{ user_profile.description }}  </li>
    {% if user_profile.image %}
    <li>image : <img style="width: auto; height: 300px;" src="{{ user_profile.image.url }}" /> </li>
    {% endif %}
</ul>
{% if form %}
<h2>수정하기</h2>
{% if user_profile.image %}
<span>image :</span> <img style="width: auto; height: 300px;" src="{{ user_profile.image.url }}" /> 
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    <div class="form-group">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-primary" type="submit" value="Update">
    </div>
</form>
{% endif %}
{% endblock %}

R01/intranet/templates/intra/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
    {% endblock %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@700&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/app.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
        <a class ="navbar-brand" href="home">장고 게시판</a>

    </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
 </body>
</html>